### Aufgabe 4 (Typ C)
Erstellen Sie ein Dictionary und weisen Sie es einer Variablen zu. Hierbei soll die Struktur von
folgendem Dictionary übernommen werden, die Werte können individuell gewählt werden :      
{'Name': ['Hans', 'Kurt', 'Heidi', 'Babs', 'Lola'],     
'RRsys': [121, 134, 155, 135, 140],     
'RRdiast': [82, 91, 93, 72, 85],     
'Puls': [62, 71, 65, 68, 59]}    
### a)    
Erzeugen Sie aus dem Dictionary ein DataFrame datafr. Als Index sollen die Zeichenketten
'PatA', 'PatB', 'PatC', 'PatD', 'PatE'verwendet werden. Geben Sie dieses DataFrame
am Bildschirm aus.

In [1]:
import pandas as pd #Package Pandas wird importiert und unter dem shortname pd gespeichert
stark={'Name':['Jon','Arya', 'Sansa','Bran', 'Rickon', 'Robb','Catlyn','Eddard'], #Dictionary wird erstellt mit Listen als Values 
      'RRsys':[121, 130, 150, 140, 131, 151, 142, 133],
      'RRdiast':[82, 91, 93, 72, 85, 80, 88, 90],
      'Puls':[62, 71, 65, 68, 59, 60, 63, 64]}
stark_df=pd.DataFrame(stark) #unter der Variable stark_df wird das Dataframe gespeichert. Die Funktion DataFrame nimmt als Argument das Dictionary und wandelt es in ein Dataframe um.
stark_df.index=['PatA', 'PatB', 'PatC', 'PatD', 'PatE', 'PatF', 'PatG', 'PatH']#Die Methode Index verteilt die Indizes an die einzelnen Datensatzzeilen. Dadurch wird sozusagen ein Primärschlüssel festgelegt.
print(stark_df)#das Dataframe wird ausgegeben

        Name  RRsys  RRdiast  Puls
PatA     Jon    121       82    62
PatB    Arya    130       91    71
PatC   Sansa    150       93    65
PatD    Bran    140       72    68
PatE  Rickon    131       85    59
PatF    Robb    151       80    60
PatG  Catlyn    142       88    63
PatH  Eddard    133       90    64

### b)
Geben Sie durch den entsprechenden Zugriff auf das DataFrame am Bildschirm aus:    
I. den zweiten und dritten Datensatz (2 syntaktische Varianten)     
II. alle RRsyst-Werte (2 syntaktische Varianten)     
III. die RRsyst-Werte von PatC und PatE     
IV. den RRsyst-Wert des zweiten Datensatzes     
V. die RRsyst-Wert des zweiten bis vierten Datensatzes     
VI. den Datensatz von PatC    
VII. die Datensätze von PatC bis PatE    
VIII. Ändern Sie den RRsyst-Werte von PatB zu 125 und geben Sie zur Kontrolle das veränderte    
DataFrame am Bildschirm aus    
IX. Fügen Sie einen neuen Datensatz (für PatF) hinzu und geben Sie zur Kontrolle das veränderte    
DataFrame am Bildschirm aus    
X. Löschen Sie den Datensatz von PatC und geben Sie zur Kontrolle das veränderte DataFrame
am Bildschirm aus

In [2]:
print('\nIa.)')#variante1 mit der loc Funktion und den Primärschlüsseln.
print(stark_df.loc[['PatB','PatC']])#Doppelt eckige Klammern erzeugen ein DataFrame Objekt. Einfach eckige Klammern erzeugen ein Series Objekt.

print('\nIb.)')#variante2 mit Index Slicing.Erster Wert inklusiv, zweiter exklusiv.
print(stark_df[1:3])

print('\nIIa.)')#variante 1
print(stark_df[["RRsys"]])#Zugriff über den Spaltenbezeichner

print('\nIIb.)')#variante 2  mit der Loc Funktion. Der erste Index ist leer, bedeutet dass alle Zeilen ausgegeben werden, zweiter Index mit Spaltenbezeichner. Nur die Spalte wird ausgegeben.
print(stark_df.loc[:,['RRsys']])

print('\nIII.)')#RRsys von Pat C und E
print(stark_df.loc[['PatC','PatE'],['RRsys']])#Loc Funktion, erster Index die gewünschten Zeilen(via PK), zweiter Index gewünschte Spaltenbezeichner

print('\nIV.)')#RRsys vom zweiten Datensatz
print(stark_df.iloc[[1],[1]])#Iloc Funktion greift über die Zahl Indizes auf die Elemente zu. Index 1=zweite Zeile,Index2=zweite Spalte='RRsys'

print('\nV.)')#RRsys von zweiter bis 4.Datensatz 
print(stark_df.iloc[1:4,[1]])#Slicing im ersten Index, zweiter Index für RRsys

print('\nVI.)')#Alles von PatC
print(stark_df.loc[['PatC']])#Pat C als PK Index mit der Loc Funktion

print('\nVII.)')#würde auch mit iloc funktionieren und Zahlenindex
print(stark_df.loc[['PatC','PatD','PatE']]) #alles von PatC;D;E wird ausgegeben

print('\nVIII.)')#Neuer Wert für PatB in RRsys 
stark_df.iloc[1,1]=[125]#Pat und Spalte über Iloc Funktion und Zahlenindex auswählen und neuen Wert zuweisen. Wert muss auch in eckigen Klammern stehen.
print(stark_df)#verändertes DataFrame wird ausgegeben

print('\nIX.)')#neuer Pat wird dem DataFrame zugewiesen
stark_df.loc['PatI',:]=['Theon',130,80,70]#mit Loc Methode PK wird erstellet. Werte werden zugewisen durch Zuweisungsoperator
print(stark_df)#erweitertes DataFrame wird ausgegeben

print('\nX.)')
stark_df_oC=stark_df.drop(['PatC'])#Pat C wird gelöscht. Mit Drop Funktion. Das Ergebnis der Funktion muss einer Variable zugewiesen werden um ein DataFrame ohne Pat C zu speichern. Das Original bleibt unverändert.
print(stark_df_oC)#DataFrame ohne Pat C wird ausgegeben.

Ia.)
       Name  RRsys  RRdiast  Puls
PatB   Arya    130       91    71
PatC  Sansa    150       93    65

Ib.)
       Name  RRsys  RRdiast  Puls
PatB   Arya    130       91    71
PatC  Sansa    150       93    65

IIa.)
      RRsys
PatA    121
PatB    130
PatC    150
PatD    140
PatE    131
PatF    151
PatG    142
PatH    133

IIb.)
      RRsys
PatA    121
PatB    130
PatC    150
PatD    140
PatE    131
PatF    151
PatG    142
PatH    133

III.)
      RRsys
PatC    150
PatE    131

IV.)
      RRsys
PatB    130

V.)
      RRsys
PatB    130
PatC    150
PatD    140

VI.)
       Name  RRsys  RRdiast  Puls
PatC  Sansa    150       93    65

VII.)
        Name  RRsys  RRdiast  Puls
PatC   Sansa    150       93    65
PatD    Bran    140       72    68
PatE  Rickon    131       85    59

VIII.)
        Name  RRsys  RRdiast  Puls
PatA     Jon    121       82    62
PatB    Arya    125       91    71
PatC   Sansa    150       93    65
PatD    Bran    140       72    68
PatE  Rickon    131       85    59
PatF    Robb    151       80    60
PatG  Catlyn    142       88    63
PatH  Eddard    133       90    64

IX.)
        Name  RRsys  RRdiast  Puls
PatA     Jon    121       82    62
PatB    Arya    125       91    71
PatC   Sansa    150       93    65
PatD    Bran    140       72    68
PatE  Rickon    131       85    59
PatF    Robb    151       80    60
PatG  Catlyn    142       88    63
PatH  Eddard    133       90    64
PatI   Theon    123       83    63

X.)
        Name  RRsys  RRdiast  Puls
PatA     Jon    121       82    62
PatB    Arya    125       91    71
PatD    Bran    140       72    68
PatE  Rickon    131       85    59
PatF    Robb    151       80    60
PatG  Catlyn    142       88    63
PatH  Eddard    133       90    64
PatI   Theon    123       83    63

### c)
I. Überprüfen Sie, welche RRsys-Werte des DataFrames größer als oder gleich 130 sind und
geben Sie das jeweilige Ergebnis (True/False) am Bildschirm aus.    
II. Filtern Sie jetzt die Datensätze des DataFrames gemäß dieser Bedingung. Es sollen also nur
die Datensätze am Bildschirm ausgegeben werden, die größer als oder gleich 130 sind.    
III. Filtern Sie danach die Datensätze des DataFrames gemäß folgender Bedingung. Es sollen nur
die Datensätze am Bildschirm ausgegeben werden, welche die obige Bedingung erfüllen (also
deren RRsys größer als oder gleich 130 sind) und deren RRdiast größer als 80 ist.    
(Passen Sie für diese Aufgabe ggf. ihre RR-Werte im Dictionary an, sodass Sie ihr Filtern
testen können.)

In [5]:
print("\n I.)")#Vergleich ob die RRsys Werte größer gleich 130 sind
print(stark_df['RRsys']>=130)#Ergebnis wird True oder False ausgegeben. Wird mit jedem RRsys Wert des DataFrames verglichen

print("\n II.)")#wenn man den Vergleichsausdruck in den Index schreibt, wird gefiltert. Es werden nur die Werte ausgegeben
print(stark_df[stark_df['RRsys']>=130])#die beim Vergleichsausdruck True erzielen.

import numpy as np#Numpy wird importiert 
print("\n III.)")#mit der logical_and Funktion kann man zwei Vergleichsausdrücke mit AND verknüpfen.Bei And müssen beide Ausdrücke True sein, damit der Gesamtausdruck True ergibt.
stark_df[np.logical_and(stark_df['RRsys']>=130,stark_df['RRdiast']>80)]#Es werden nur die Werte ausgegeben, die bei beiden Vergleichsausdrücken True ergeben.

 I.)
PatA    False
PatB    False
PatC     True
PatD     True
PatE     True
PatF     True
PatG     True
PatH     True
PatI    False
Name: RRsys, dtype: bool

 II.)
        Name  RRsys  RRdiast  Puls
PatC   Sansa    150       93    65
PatD    Bran    140       72    68
PatE  Rickon    131       85    59
PatF    Robb    151       80    60
PatG  Catlyn    142       88    63
PatH  Eddard    133       90    64

 III.)

        Name  RRsys  RRdiast  Puls
PatC   Sansa    150       93    65
PatE  Rickon    131       85    59
PatG  Catlyn    142       88    63
PatH  Eddard    133       90    64